language: python

python:
    - "2.7"

services:
    - docker

before_install:
    - chmod +x ./tests/ci/install_environment.sh
    - ./tests/ci/install_environment.sh

install:
    - chmod +x ./tests/ci/install_nuocd.sh
    - ./tests/ci/install_nuocd.sh

before_script:
    - sleep 120

script:
    - pip install -r test_requirements.txt
    - python ./run_tests.py
    - echo "Done"
