language: python

python:
    - "2.7"

services:
    - docker

jobs:
  include:
      - stage: Test
        install:
            - chmod +x ./tests/ci/install_environment.sh
            - ./tests/ci/install_environment.sh
            - chmod +x ./tests/ci/install_nuocd.sh
            - ./tests/ci/install_nuocd.sh
        install:
            - docker-compose up&

before_script:
    - sleep 120

script:
    - pip install -r test_requirements.txt
    - python ./run_tests.py
    - echo "Done"

