language: python

python:
    - "2.7"

services:
    - docker

env:
  - TEST_SUITE="Bare Metal"
  - TEST_SUITE="Docker"

install:
    - ./tests/ci/determine_and_run_tests.sh

before_script:
    - sleep 120

script:
    - pip install -r test_requirements.txt
    - python ./run_tests.py
    - echo "Done"

