version: "3.7"
services:
  nuoadmin1:
    image: $DOCKER_IMAGE
    environment:
      NUODB_DOMAIN_ENTRYPOINT: nuoadmin1
      NUOCMD_API_SERVER: http://nuoadmin1:8888
    hostname: nuoadmin1
    command: ["nuoadmin", "--", "ssl=false"]
  sm:
    image: $DOCKER_IMAGE
    hostname: sm
    environment:
      NUOCMD_API_SERVER: http://nuoadmin1:8888
    depends_on: 
    - nuoadmin1
    command: ["nuodocker", "start", "sm", "--db-name", "hockey", "--server-id", "nuoadmin1", "--dba-user", "dba", "--dba-password", "goalie"]
  te:
    image: $DOCKER_IMAGE
    hostname: te
    environment:
      NUOCMD_API_SERVER: http://nuoadmin1:8888
    depends_on: 
    - nuoadmin1
    - sm
    command: ["nuodocker", "start", "te", "--db-name", "hockey", "--server-id", "nuoadmin1"]
  influxdb:
    image: influxdb:latest
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
  nuocd-sm:
    build: .
    depends_on:
    - nuoadmin1
    - sm
    - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCMD_API_SERVER: http://nuoadmin1:8888
      NUOCD_HOSTNAME: sm
    pid: 'service:sm'
  nuocd-te:
    build: .
    depends_on:
      - nuoadmin1
      - sm
      - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCMD_API_SERVER: http://nuoadmin1:8888
      NUOCD_HOSTNAME: te
    pid: 'service:te'