version: "3.3"
services:
  nuoadmin1:
    image: $DOCKER_IMAGE
    environment:
      NUODB_DOMAIN_ENTRYPOINT: nuoadmin1
    hostname: nuoadmin1
    restart: unless-stopped
    command: ["nuoadmin"]
  sm:
    image: $DOCKER_IMAGE
    hostname: sm
    restart: unless-stopped
    environment:
      NUOCMD_API_SERVER: nuoadmin1:8888
    depends_on:
    - nuoadmin1
    command: ["nuodocker", "start", "sm", "--db-name", "hockey", "--server-id", "nuoadmin1",
        "--dba-user", "dba", "--dba-password", "goalie",
        "--servers-ready-timeout", "60"]
  te:
    image: $DOCKER_IMAGE
    hostname: te
    restart: unless-stopped
    environment:
      NUOCMD_API_SERVER: nuoadmin1:8888
    depends_on:
    - nuoadmin1
    - sm
    command: ["nuodocker", "start", "te", "--db-name", "hockey", "--server-id", "nuoadmin1",
          "--servers-ready-timeout", "60"]
  influxdb:
    image: influxdb:2.7.1
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
  nuocd-sm:
    build: .
    restart: unless-stopped
    depends_on:
    - nuoadmin1
    - sm
    - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCMD_API_SERVER: nuoadmin1:8888
      NUOCD_HOSTNAME: sm
    pid: 'service:sm'
  nuocd-te:
    build: .
    restart: unless-stopped
    depends_on:
      - nuoadmin1
      - sm
      - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCMD_API_SERVER: nuoadmin1:8888
      NUOCD_HOSTNAME: te
    pid: 'service:te'
  nuocd-admin1:
    build: .
    restart: unless-stopped
    depends_on:
      - nuoadmin1
      - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCMD_API_SERVER: https://nuoadmin1:8888
      NUOCD_HOSTNAME: nuoadmin1
    pid: 'service:nuoadmin1'