version: 2.1

jobs:
  test_docker:
    machine:
      image: default
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Export all environment variables in .env
          command: |
            sed -n 's/\(.*=\)/export \1/p' .env >> "$BASH_ENV"
      - run:
          name: Create domain and database
          command: |
            docker compose up --wait --wait-timeout 120
      - run:
          name: Wait all processes to become ready
          command: |
            nuoadmin="$(docker container ls -f name=nuoadmin -q)"
            docker exec "$nuoadmin" nuocmd check servers --check-connected --check-converged --timeout 300
            docker exec "$nuoadmin" nuocmd check database --db-name hockey --check-running --num-processes 2 --timeout 300
      - run:
          name: Configure and run tests
          command: |
            pip3 install -r test_requirements.txt
            pytest --junitxml=test_results/result.xml
      - run:
          name: Output container logs on failure
          command: |
            docker compose logs
          when: on_fail
      - store_test_results:
          path: test_results

workflows:
  build-project:
    jobs:
      - test_docker
