version: 2.1

commands:
  nuodb_collector_command:
    steps:
      - checkout
      - run:
          name : Run dependencies
          command: ./tests/ci/determine_and_run_tests.sh
      - run:
          name : Take a nap
          command: |
            sleep 15
      - run:
          name : Configure and run tests
          command: |
            pip3 install -r test_requirements.txt
            pytest --junitxml=test_results/result.xml
            echo "Done"
      - store_test_results:
          path: test_results

jobs:
  build_n_run_docker:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - nuodb_collector_command
    environment:
      TEST_SUITE: Docker
      INFLUXDB_TOKEN: quickbrownfoxjumpsoveralazydog
      INFLUXDB_ORG: nuodb
    resource_class: medium

  build_n_run_bare_metal:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - nuodb_collector_command
    environment:
      TEST_SUITE: "Bare Metal"
    resource_class: medium

workflows:
  build-project:
    jobs:
      - build_n_run_docker
      # - build_n_run_bare_metal